---
- name: "Mac Deployment"
  hosts: localhost
  connection: local
  become: false

  vars:
    brew_casks:
      - alfred
      - iterm2
      - sublime-text
      - visual-studio-code

    brew_packages:
      - ansible-lint
      - neofetch
      - yamllint
      - vim
      - zsh-autosuggestions
      - zsh-history-substring-search

  tasks:
    - name: "chrisvanmeer.homebrew : Ensure Homebrew is updated."
      homebrew:
        update_homebrew: yes

    - name: "chrisvanmeer.homebrew : Ensure Homebrew casks are poured."
      homebrew_cask:
        name: "{{ brew_casks }}"
        state: present
      when: install_brew_casks is defined

    - name: "chrisvanmeer.homebrew : Ensure Homebrew packages are present."
      homebrew:
        name: "{{ brew_packages }}"
        state: present

    - name: "chrisvanmeer.zsh : Ensure oh-my-zsh is installed."
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: ~/.oh-my-zsh
      tags: zsh

    - name: "chrisvanmeer.zsh : Ensure zsh-history-substring-search plugin is installed."
      git:
        repo: https://github.com/zsh-users/zsh-history-substring-search
        dest: ~/.oh-my-zsh/custom/plugins/zsh-history-substring-search
      tags: zsh

    - name: "chrisvanmeer.zsh : Ensure zsh-autosuggestions plugin is installed."
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions
      tags: zsh

  roles:
    - role: chrisvanmeer.dotfiles
      tags: dotfiles
    - role: chrisvanmeer.vim
      tags: vim
