---
- name: "Mac Deployment"
  hosts: all
  become: false

  vars:

    home_path: "~"

    brew_casks:
      - alfred
      - bartender
      - iterm2
      - sequel-ace
      - sublime-text
      - transmit
      - visual-studio-code

    brew_formulae:
      - ansible-lint
      - git
      - iperf
      - neofetch
      - nmap
      - tmux
      - tree
      - wget
      - vim
      - yamllint
      - zsh-autosuggestions
      - zsh-history-substring-search
      - zsh-syntax-highlighting

  roles:
    - role: geerlingguy.mac.homebrew
      tags: homebrew
    - role: chrisvanmeer.dotfiles
      tags: dotfiles

  tasks:
    - name: "chrisvanmeer.homebrew : Ensure Homebrew casks are poured."
      homebrew_cask:
        name: "{{ brew_casks }}"
        state: present
      when: install_brew_casks is defined
      tags: homebrew

    - name: "chrisvanmeer.homebrew : Ensure Homebrew formulae are present."
      homebrew:
        name: "{{ brew_formulae }}"
        state: present
      tags: homebrew

    - name: "chrisvanmeer.zsh : Retrieve current user's shell."
      set_fact:
        current_user_shell: "{{ ansible_user_shell }}"
      tags: zsh

    - name: "chrisvanmeer.zsh : Ensure zsh is set as shell if current shell is not already zsh."
      shell: chsh -s $(which zsh) {{ lookup('env', 'USER') }}
      become: true
      when: current_user_shell != "/bin/zsh"
      tags: zsh

    - name: "chrisvanmeer.zsh : Ensure oh-my-zsh is installed."
      git:
        repo: https://github.com/robbyrussell/oh-my-zsh
        dest: "{{ home_path }}/.oh-my-zsh"
      tags: zsh

    - name: "chrisvanmeer.zsh : Ensure zsh-history-substring-search plugin is installed."
      git:
        repo: https://github.com/zsh-users/zsh-history-substring-search
        dest: "{{ home_path }}/.oh-my-zsh/custom/plugins/zsh-history-substring-search"
      tags: zsh

    - name: "chrisvanmeer.zsh : Ensure zsh-autosuggestions plugin is installed."
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: "{{ home_path }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
      tags: zsh

    - name: "chrisvanmeer.zsh : Ensure zsh-syntax-highlighting plugin is installed."
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: "{{ home_path }}/zsh-syntax-highlighting"
      tags: zsh

    - name: "chrisvanmeer.vim : Check if indentLine plugin is installed."
      stat:
        path: "{{ home_path }}/.vim/pack/vendor/start/indentLine"
      become: false
      register: identline
      tags: vim

    - name: "chrisvanmeer.vim : Clone indentLine repo if identLine is not installed."
      git:
        repo: https://github.com/Yggdroot/indentLine.git
        dest: "{{ home_path }}/.vim/pack/vendor/start/indentLine"
      become: false
      when: not identline.stat.exists
      tags: vim

    - name: "chrisvanmeer.vim : Register identLine plugin if identLine is not installed."
      command: 'vim -u NONE -c "helptags {{ home_path }}/.vim/pack/vendor/start/indentLine/doc" -c "q"'
      become: false
      when: not identline.stat.exists
      tags: vim

    - name: "chrisvanmeer.yaml : Ensure yamllint configuration directory is in place."
      file:
        path: "{{ home_path }}/.config/yamllint"
        state: directory
      become: false
      tags: yaml

    - name: "chrisvanmeer.yaml : Ensure yamllint configuration is in place."
      copy:
        dest: "{{ home_path }}/.config/yamllint/config"
        content: |
          extends: relaxed
          rules:
            line-length: disable
      become: false
      tags: yaml
